spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:ssl/quiz.p12
    key-store-type: PKCS12
    key-store-password: ${TLS_KEYSTORE_PASSWORD}
    key-alias: quiz

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000