spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
signature:
  key-store-path: classpath:ssl/signing.jks
  key-store-type: JKS
  key-store-password: changeit
  key-alias: signing
  key-password: changeit